import { db } from './index.ts';
import * as schema from './schema.ts';
import { eq } from 'drizzle-orm';
import { persistProductToFirestore, persistPackageToFirestore } from '../services/firestoreSync.ts';

/**
 * Seed master static reference tables: Staff users, Operators, Properties, Categories,
 * Knowledge sources, and School trip commercial tariffs.
 * These tables are required as foreign key targets for products, reservations, and rooms.
 */
export async function seedMasterReferenceData() {
  // 1. Staff Users
  const staffUsers = [
    {
      id: 'usr_coord_1',
      email: 'reservations@syntuc.com',
      name: 'Victoria Falls Reservations Desk',
      role: 'reservations_coordinator',
      isActive: true,
      passwordHash: 'syntuc2026!secure',
    },
    {
      id: 'usr_admin_1',
      email: 'admin@saintech.io',
      name: 'SAINTECH System Admin',
      role: 'admin',
      isActive: true,
      passwordHash: 'saintech2026!admin',
    },
    {
      id: 'usr_user_email',
      email: 'tatenda.muvezwa@gmail.com',
      name: 'Tatenda Muvezwa',
      role: 'admin',
      isActive: true,
      passwordHash: 'admin2026!',
    }
  ];

  for (const u of staffUsers) {
    await db.insert(schema.users).values(u).onConflictDoNothing();
  }

  // 2. Operators
  const ops = [
    {
      id: 'op_shearwater',
      name: 'Shearwater Victoria Falls',
      contactEmail: 'adventures@shearwatervf.com',
      contactPhone: '+263 83 284 4471',
      location: 'Victoria Falls, Zimbabwe',
      description: 'Premier adventure and touring operator in Victoria Falls since 1982.',
      verified: true,
    },
    {
      id: 'op_wildhorizons',
      name: 'Wild Horizons',
      contactEmail: 'info@wildhorizons.co.zw',
      contactPhone: '+263 83 284 4219',
      location: 'Victoria Falls, Zimbabwe',
      description: 'Pioneers in high-end eco-tourism, wildlife sanctuaries, and scenic flights.',
      verified: true,
    },
    {
      id: 'op_rtg',
      name: 'Rainbow Tourism Group (RTG)',
      contactEmail: 'reservations@rtg.co.zw',
      contactPhone: '+263 83 284 4583',
      location: 'Victoria Falls, Zimbabwe',
      description: 'Leading hospitality group operating the Victoria Falls Rainbow Hotel.',
      verified: true,
    },
    {
      id: 'op_cresta',
      name: 'Cresta Hotels Zimbabwe',
      contactEmail: 'azambezi@cresta.co.zw',
      contactPhone: '+263 83 284 4561',
      location: 'Victoria Falls, Zimbabwe',
      description: 'Operators of A\'Zambezi River Lodge on the banks of the Zambezi.',
      verified: true,
    },
    {
      id: 'op_pure_africa',
      name: 'Pure Africa Experiences',
      contactEmail: 'experience@pure.africa',
      contactPhone: '+263 83 284 1005',
      location: 'Victoria Falls, Zimbabwe',
      description: 'Operators of the Zambezi Explorer and The Eatery Waterfront dining.',
      verified: true,
    },
    {
      id: 'op_machaba',
      name: 'Machaba Safaris',
      contactEmail: 'enquiries@machabasafaris.com',
      contactPhone: '+27 82 579 5249',
      location: 'Zambezi National Park, Zimbabwe',
      description: 'Luxury classic safari camps including Old Drift Lodge.',
      verified: true,
    }
  ];

  for (const op of ops) {
    await db.insert(schema.operators).values(op).onConflictDoNothing();
  }

  // 3. Properties
  const props = [
    {
      id: 'prop_azambezi',
      operatorId: 'op_cresta',
      name: 'A\'Zambezi River Lodge',
      propertyType: 'Lodge',
      address: '308 Parkway Drive, Victoria Falls',
      checkInTime: '14:00',
      checkOutTime: '10:00',
      amenities: ['Direct Zambezi River Frontage', 'Riverfront Pool', 'Wildlife on Grounds', 'Boat Jetty', 'Free Town Shuttle', 'Amulonga Restaurant'],
    },
    {
      id: 'prop_rainbow',
      operatorId: 'op_rtg',
      name: 'Victoria Falls Rainbow Hotel',
      propertyType: 'Hotel',
      address: '281 Parkway Drive, Victoria Falls',
      checkInTime: '14:00',
      checkOutTime: '10:00',
      amenities: ['Panorama Spray Deck', 'Swimming Pool & Swim-up Bar', 'Simunye Theatre Onsite', 'Conference Facilities', 'Walking Distance to Town'],
    },
    {
      id: 'prop_explorers',
      operatorId: 'op_shearwater',
      name: 'Shearwater Explorers Village',
      propertyType: 'Village',
      address: 'Adam Stander Drive, Victoria Falls',
      checkInTime: '14:00',
      checkOutTime: '10:00',
      amenities: ['Central Location 400m from Town', 'Two Swimming Pools', 'Lush Tropical Gardens', 'Courtyard Restaurant & Bar', 'Activity Booking Desk'],
    },
    {
      id: 'prop_olddrift',
      operatorId: 'op_machaba',
      name: 'Old Drift Lodge',
      propertyType: 'Safari Camp',
      address: 'Zambezi National Park Riverfront',
      checkInTime: '13:00',
      checkOutTime: '10:30',
      amenities: ['All-Inclusive Luxury', 'Private Plunge Pools', 'Outdoor Safari Bath', 'River Boat Safaris', 'Game Drives in National Park', 'Eco-Solar Powered'],
    },
    {
      id: 'prop_elephantcamp',
      operatorId: 'op_wildhorizons',
      name: 'The Elephant Camp',
      propertyType: 'Safari Camp',
      address: 'Victoria Falls Private Game Reserve',
      checkInTime: '13:00',
      checkOutTime: '10:30',
      amenities: ['Private Concession Overlooking Gorge', 'Private Deck & Plunge Pool', 'Elephant Sanctuary Interaction', 'All-Inclusive Fine Dining', 'Victoria Falls Spray Views'],
    }
  ];

  for (const pr of props) {
    await db.insert(schema.properties).values(pr).onConflictDoNothing();
  }

  // 4. Categories
  const cats = [
    { id: 'cat_lodge', slug: 'lodge-resort', name: 'Riverfront Lodges & Resorts', type: 'accommodation', displayOrder: 1 },
    { id: 'cat_hotel', slug: 'hotel', name: 'Town Hotels & Suites', type: 'accommodation', displayOrder: 2 },
    { id: 'cat_safari', slug: 'safari-camp', name: 'Luxury Safari Camps', type: 'accommodation', displayOrder: 3 },
    { id: 'cat_flight', slug: 'flight-air', name: 'Helicopter & Scenic Flights', type: 'activity', displayOrder: 4 },
    { id: 'cat_cruise', slug: 'river-cruises', name: 'Zambezi River Cruises', type: 'activity', displayOrder: 5 },
    { id: 'cat_guided', slug: 'guided-tours', name: 'Guided Falls & Heritage Tours', type: 'activity', displayOrder: 6 },
    { id: 'cat_dining', slug: 'dining-culinary', name: 'Scenic & Cultural Dining', type: 'activity', displayOrder: 7 },
    { id: 'cat_adventure', slug: 'adventure-wildlife', name: 'Rafting, Wildlife & Adrenaline', type: 'activity', displayOrder: 8 },
    { id: 'cat_packages', slug: 'packages', name: 'Curated Holiday Packages', type: 'package', displayOrder: 9 },
  ];

  for (const c of cats) {
    await db.insert(schema.categories).values(c).onConflictDoNothing();
  }

  // Knowledge Sources (Traceability)
  const sources = [
    {
      id: 'ks_shearwater_contract',
      name: 'Shearwater 2026 Authoritative Tariff Schedule',
      sourceUrl: 'https://shearwatervictoriafalls.com/tariffs/2026',
      sourceType: 'operator_contract',
      evidenceStatus: 'ESTABLISHED',
      notes: 'Authoritative contracted agent rates for Flight of Angels, Bridge Tours, and White Water Rafting.',
    },
    {
      id: 'ks_zimparks_2026',
      name: 'ZimParks Official Conservation Fees Gazette 2026',
      sourceUrl: 'https://zimparks.org.zw/tariffs',
      sourceType: 'zimparks_official',
      evidenceStatus: 'ESTABLISHED',
      notes: 'National Park entry fees: Victoria Falls Rainforest ($50 intl), Zambezi River ($12), Batoka Gorge ($10).',
    },
    {
      id: 'ks_school_commercial_tariff',
      name: 'Victoria Falls Educational Commercial Tariff Schedule 2026',
      sourceUrl: 'internal://commercial-tariffs/schools-2026',
      sourceType: 'commercial_tariff',
      evidenceStatus: 'ESTABLISHED',
      notes: 'Authoritative frozen rules for school groups: accommodation starting $15/child, Rainbow Hotel $130/room shared by 2 children, teacher rules, Bridge Tour incentive qualification.',
    }
  ];

  for (const s of sources) {
    await db.insert(schema.knowledgeSources).values(s).onConflictDoNothing();
  }

  // School Trip Commercial Tariffs (Frozen Commercial Rules)
  const schoolTariffs = [
    {
      id: 'st_budget_lodge',
      itemCategory: 'accommodation',
      itemName: 'Budget School Lodge (Khulula / Teak / Reynard / Letsatsi)',
      targetTier: 'budget',
      rateAmount: '15.00',
      rateBasis: 'per_child_per_night',
      isBridgeIncentiveQualifying: false,
      notes: 'Starting commercial rate from USD 15 per child per night. Subject to group availability.',
    },
    {
      id: 'st_rainbow_hotel',
      itemCategory: 'accommodation',
      itemName: 'Victoria Falls Rainbow Hotel (School Tier)',
      targetTier: 'rainbow_hotel',
      rateAmount: '130.00',
      rateBasis: 'per_room_shared_2_children',
      isBridgeIncentiveQualifying: false,
      notes: 'USD 130 per room shared by two children (equals USD 65 per child per night).',
    },
    {
      id: 'st_boat_cruise',
      itemCategory: 'activity',
      itemName: 'Standard Zambezi River Boat Cruise',
      targetTier: 'student',
      rateAmount: '10.00',
      rateBasis: 'per_child',
      isBridgeIncentiveQualifying: false,
      notes: 'USD 10 per child. Plus park fees: Primary USD 1, Secondary USD 4. Does NOT count toward Bridge Tour qualification.',
    },
    {
      id: 'st_croc_farm_primary',
      itemCategory: 'activity',
      itemName: 'Crocodile Farm (Primary School)',
      targetTier: 'primary',
      rateAmount: '3.00',
      rateBasis: 'per_child',
      isBridgeIncentiveQualifying: false,
      notes: 'Primary school rate USD 3 per child.',
    },
    {
      id: 'st_croc_farm_secondary',
      itemCategory: 'activity',
      itemName: 'Crocodile Farm (Secondary School)',
      targetTier: 'secondary',
      rateAmount: '4.00',
      rateBasis: 'per_child',
      isBridgeIncentiveQualifying: false,
      notes: 'Secondary school rate USD 4 per child.',
    },
    {
      id: 'st_rainforest_primary',
      itemCategory: 'activity',
      itemName: 'Victoria Falls Rainforest Walking Tour (Primary)',
      targetTier: 'primary',
      rateAmount: '1.00',
      rateBasis: 'per_child',
      isBridgeIncentiveQualifying: false,
      notes: 'Primary school student entry USD 1.',
    },
    {
      id: 'st_rainforest_secondary',
      itemCategory: 'activity',
      itemName: 'Victoria Falls Rainforest Walking Tour (Secondary)',
      targetTier: 'secondary',
      rateAmount: '4.00',
      rateBasis: 'per_child',
      isBridgeIncentiveQualifying: false,
      notes: 'Secondary school student entry USD 4.',
    },
    {
      id: 'st_rainforest_adult',
      itemCategory: 'activity',
      itemName: 'Victoria Falls Rainforest Walking Tour (Teacher/Adult Standard)',
      targetTier: 'teacher',
      rateAmount: '7.00',
      rateBasis: 'per_adult',
      isBridgeIncentiveQualifying: false,
      notes: 'Standard adult/teacher entry USD 7. Exemption applies for 1 teacher per 20 students.',
    },
    {
      id: 'st_rainforest_teacher_exempt',
      itemCategory: 'activity',
      itemName: 'Victoria Falls Rainforest Teacher Exemption (1 per 20 students)',
      targetTier: 'teacher',
      rateAmount: '4.00',
      rateBasis: 'per_adult',
      isBridgeIncentiveQualifying: false,
      notes: 'Teacher rule: 1 teacher per 20 children receives half-price exemption at USD 4 (Rainforest tour ONLY).',
    },
    {
      id: 'st_helicopter',
      itemCategory: 'activity',
      itemName: 'School Educational Helicopter Flight',
      targetTier: 'student',
      rateAmount: '70.00',
      rateBasis: 'per_child',
      isBridgeIncentiveQualifying: true,
      notes: 'Special educational flight tariff USD 70 per person/child. Priority activity for Bridge Tour incentive.',
    },
    {
      id: 'st_quad_biking',
      itemCategory: 'activity',
      itemName: 'Supervised Quad Biking',
      targetTier: 'student',
      rateAmount: '10.00',
      rateBasis: 'per_child',
      isBridgeIncentiveQualifying: true,
      notes: 'USD 10 per child. Priority activity for Bridge Tour incentive.',
    },
    {
      id: 'st_airport_tour',
      itemCategory: 'activity',
      itemName: 'Airport Educational Aviation Tour',
      targetTier: 'student',
      rateAmount: '3.00',
      rateBasis: 'per_child',
      isBridgeIncentiveQualifying: false,
      notes: 'USD 3 per child.',
    },
    {
      id: 'st_elephant_primary',
      itemCategory: 'activity',
      itemName: 'Elephant Interaction Sanctuary (Primary)',
      targetTier: 'primary',
      rateAmount: '10.00',
      rateBasis: 'per_child',
      isBridgeIncentiveQualifying: true,
      notes: 'Primary school USD 10 per child. Priority activity for Bridge Tour incentive.',
    },
    {
      id: 'st_elephant_secondary',
      itemCategory: 'activity',
      itemName: 'Elephant Interaction Sanctuary (Secondary)',
      targetTier: 'secondary',
      rateAmount: '20.00',
      rateBasis: 'per_child',
      isBridgeIncentiveQualifying: true,
      notes: 'Secondary school USD 20 per child. Priority activity for Bridge Tour incentive.',
    },
    {
      id: 'st_sunset_cruise_drive',
      itemCategory: 'activity',
      itemName: 'Sunset Cruise and Game Drive (School Package)',
      targetTier: 'student',
      rateAmount: '25.00',
      rateBasis: 'per_child',
      isBridgeIncentiveQualifying: true,
      notes: 'Qualifies as priority activity for Bridge Tour incentive.',
    },
    {
      id: 'st_bridge_tour_standard',
      itemCategory: 'activity',
      itemName: 'Victoria Falls Historic 1905 Bridge Tour',
      targetTier: 'standard',
      rateAmount: '20.00',
      rateBasis: 'per_child',
      isBridgeIncentiveQualifying: false,
      notes: 'Standard school tariff USD 20/child. Becomes USD 0 (COMPLIMENTARY) when group books >=2 nights accommodation AND >=2 qualifying priority activities.',
    }
  ];

  for (const st of schoolTariffs) {
    await db.insert(schema.schoolTripTariffs).values(st).onConflictDoNothing();
  }
}

/**
 * Seed bootstrap catalog items (products, rooms, packages, and fallback media).
 * STRICT RULE: Cloud Firestore state ALWAYS takes precedence.
 * If a product, package, or media asset already exists in the database (restored from Firestore)
 * or has an active deletion tombstone, this bootstrap seeding WILL NEVER OVERWRITE OR RESURRECT IT.
 */
export async function seedBootstrapCatalog(tombstones: Set<string> = new Set()) {
  // 5. Products (15 Canonical Products: 5 Accommodation + 10 Activities)
  const prods = [
    // --- ACCOMMODATION (5) ---
    {
      id: 'prod_azambezi',
      operatorId: 'op_cresta',
      propertyId: 'prop_azambezi',
      name: 'A\'Zambezi River Lodge',
      slug: 'azambezi-river-lodge',
      productType: 'accommodation',
      categorySlug: 'lodge-resort',
      shortDescription: 'The only hotel in Victoria Falls with direct river frontage on the majestic Zambezi River.',
      description: 'Nestled on the banks of the mighty Zambezi River right at the edge of Zambezi National Park, A\'Zambezi River Lodge combines warm Zimbabwean hospitality with unspoiled wilderness views. Warthogs and bushbucks roam the rolling lawns down to the river jetty. Guests enjoy riverside dining at the Amulonga Restaurant, sunset drinks on the deck, and complimentary shuttles to Victoria Falls town and rainforest.',
      location: 'Parkway Drive, Victoria Falls Riverfront',
      duration: 'Per night stay',
      basePrice: '220.00',
      currency: 'USD',
      priceBasis: 'per_room_night',
      inclusions: ['Full buffet breakfast', 'Complimentary shuttle service to Victoria Falls Rainforest & town', 'Wi-Fi throughout property', 'Access to riverside pool and wildlife grounds'],
      exclusions: ['National park entry fees', 'Personal bar accounts', 'Laundry services'],
      suitability: ['Couples & Honeymooners', 'Families with children', 'Wildlife enthusiasts', 'Relaxation seekers'],
      isPublished: true,
      isFeatured: true,
      availabilityNote: 'Subject to partner confirmation',
      primaryMediaId: 'med_azambezi_main',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_rainbow',
      operatorId: 'op_rtg',
      propertyId: 'prop_rainbow',
      name: 'Victoria Falls Rainbow Hotel',
      slug: 'victoria-falls-rainbow-hotel',
      productType: 'accommodation',
      categorySlug: 'hotel',
      shortDescription: 'Centrally situated hotel famous for its unique Moorish architecture and Panorama Deck overlooking the Falls spray.',
      description: 'Victoria Falls Rainbow Hotel is located beside Victoria Falls town, renowned for its distinctive rooftop Panorama Deck where guests can witness the rising misty spray of the Falls while sipping sundowners. Featuring spacious air-conditioned rooms, a lively swim-up pool bar, and on-site Simunye theatrical performances, it provides an unbeatable base for discovering the region.',
      location: 'Parkway Drive, Victoria Falls Town',
      duration: 'Per night stay',
      basePrice: '165.00',
      currency: 'USD',
      priceBasis: 'per_room_night',
      inclusions: ['Full English breakfast', 'Free high-speed Wi-Fi', 'Swimming pool & sun loungers', 'Panorama Deck access for Falls spray viewing'],
      exclusions: ['Rainforest entrance fees', 'Room service fee', 'Airport transfers'],
      suitability: ['Leisure travelers', 'School and student groups', 'Conferences', 'Families'],
      isPublished: true,
      isFeatured: true,
      availabilityNote: 'Subject to partner confirmation',
      primaryMediaId: 'med_rainbow_main',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_explorers',
      operatorId: 'op_shearwater',
      propertyId: 'prop_explorers',
      name: 'Shearwater Explorers Village',
      slug: 'shearwater-explorers-village',
      productType: 'accommodation',
      categorySlug: 'lodge-resort',
      shortDescription: 'Vibrant, beautifully landscaped retreat just 400 meters from Victoria Falls town center.',
      description: 'Shearwater Explorers Village offers a relaxed oasis in the heart of Victoria Falls. Set within indigenous gardens with two swimming pools, modern chalets, and an energetic courtyard restaurant, it is the ideal launchpad for thrill-seekers, independent travelers, and families looking for comfort and walking proximity to shops and restaurants.',
      location: 'Adam Stander Drive, Victoria Falls',
      duration: 'Per night stay',
      basePrice: '110.00',
      currency: 'USD',
      priceBasis: 'per_room_night',
      inclusions: ['Continental & hot breakfast', 'High-speed Wi-Fi', 'Two swimming pools', 'Dedicated Shearwater activity desk on site'],
      exclusions: ['Park entrance fees', 'Lunch and dinner', 'Beverages'],
      suitability: ['Adventure travelers', 'Young professionals', 'Families', 'Budget-conscious safari lovers'],
      isPublished: true,
      isFeatured: false,
      availabilityNote: 'Subject to partner confirmation',
      primaryMediaId: 'med_explorers_main',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_olddrift',
      operatorId: 'op_machaba',
      propertyId: 'prop_olddrift',
      name: 'Old Drift Lodge',
      slug: 'old-drift-lodge',
      productType: 'accommodation',
      categorySlug: 'safari-camp',
      shortDescription: 'Ultra-luxury riverside tented safari lodge tucked deep inside Zambezi National Park.',
      description: 'Steeped in 19th-century river crossing history, Old Drift Lodge offers five-star canvas luxury on a sweeping bend of the Zambezi River. Each spacious suite features a private plunge pool, outdoor roll-top Victorian bath overlooking the river, and expansive timber decks. Guests experience morning river boat safaris, 4x4 game drives in Zambezi National Park, and gourmet dining under baobab trees.',
      location: 'Zambezi National Park, 7km upstream from Victoria Falls',
      duration: 'Per night stay (All Inclusive)',
      basePrice: '680.00',
      currency: 'USD',
      priceBasis: 'per_person',
      inclusions: ['All luxury meals, snacks & high tea', 'All local spirits, premium wines, beers & soft drinks', 'Morning & afternoon river boat safaris', 'Zambezi National Park 4x4 game drives', 'Guided walking safaris', 'Victoria Falls town & rainforest return transfers'],
      exclusions: ['National park conservation fees ($15/person/day)', 'Premium imported champagne', 'Spa treatments'],
      suitability: ['Discerning luxury safari travelers', 'Romantic honeymoons', 'Photographers', 'Wildlife connoisseurs'],
      isPublished: true,
      isFeatured: true,
      availabilityNote: 'Subject to partner confirmation',
      primaryMediaId: 'med_olddrift_main',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_elephantcamp',
      operatorId: 'op_wildhorizons',
      propertyId: 'prop_elephantcamp',
      name: 'The Elephant Camp',
      slug: 'the-elephant-camp',
      productType: 'accommodation',
      categorySlug: 'safari-camp',
      shortDescription: 'Exclusive luxury wilderness retreat perched high on a ridge with vistas of the Victoria Falls spray.',
      description: 'The Elephant Camp sits within a private wildlife concession bordered by the Masuwe River and Zambezi gorges. Uniquely intimate, each luxury tented suite boasts a private plunge pool, private viewing deck, deep bathtub, and indoor and outdoor showers. Guests enjoy respectful encounters with rescued elephants at the adjacent sanctuary, along with gourmet chef cuisine and bespoke safari activities.',
      location: 'Masuwe Private Game Reserve, Victoria Falls',
      duration: 'Per night stay (All Inclusive)',
      basePrice: '750.00',
      currency: 'USD',
      priceBasis: 'per_person',
      inclusions: ['All meals and high teas', 'All drinks, cocktails and selected vintage wines', 'Elephant Sanctuary interaction encounter', 'Canopy tour / Victoria Falls transfers', 'Laundry services'],
      exclusions: ['Reserve conservation levy ($20/person/stay)', 'Top-shelf cellar reserves', 'Curio purchases'],
      suitability: ['Honeymooners', 'Wildlife & conservation advocates', 'Exclusive luxury travel', 'Celebratory milestones'],
      isPublished: true,
      isFeatured: true,
      availabilityNote: 'Subject to partner confirmation',
      primaryMediaId: 'med_elephantcamp_main',
      evidenceStatus: 'ESTABLISHED',
    },

    // --- ACTIVITIES (10) ---
    {
      id: 'prod_rainforest_walk',
      operatorId: 'op_shearwater',
      name: 'Victoria Falls Rainforest Guided Walking Tour',
      slug: 'rainforest-guided-walking-tour',
      productType: 'activity',
      categorySlug: 'guided-tours',
      shortDescription: 'Immersive guided journey through the lush rainforest viewpoints of the world\'s largest waterfall.',
      description: 'Feel the earth-shaking rumble and cool spray of "Mosi-oa-Tunya" — The Smoke That Thunders. Accompanied by a master local naturalist guide, you will walk the 16 scenic viewpoints along the edge of the chasm, from Devil\'s Cataract and the Main Falls to Rainbow Falls and the Historic Bridge viewpoint. Learn about David Livingstone\'s 1855 arrival, the geology of the basalt fissures, and the unique flora of the rainforest.',
      location: 'Victoria Falls National Park Rainforest',
      duration: '2.5 Hours',
      basePrice: '35.00',
      currency: 'USD',
      priceBasis: 'per_person',
      inclusions: ['Professional English-speaking naturalist guide', 'Rain poncho / waterproof cape', 'Bottled mineral water', 'Hotel return transfers in Victoria Falls'],
      exclusions: ['Rainforest National Park entry fee ($50 international / $30 regional / $7 local)', 'Personal souvenirs'],
      suitability: ['All ages and fitness levels', 'First-time visitors', 'Photographers'],
      isPublished: true,
      isFeatured: true,
      availabilityNote: 'Scheduled departures daily at 08:00 & 14:00',
      primaryMediaId: 'med_rainforest_main',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_flight_of_angels',
      operatorId: 'op_shearwater',
      name: 'Flight of Angels — Scenic Helicopter Tour',
      slug: 'flight-of-angels-helicopter-tour',
      productType: 'activity',
      categorySlug: 'flight-air',
      shortDescription: 'The classic 12-minute scenic helicopter flight offering unparalleled aerial views of the Falls and gorge.',
      description: 'Described by David Livingstone as "scenes so lovely must have been gazed upon by angels in their flight," this 12-minute helicopter journey lifts off over the Zambezi River. You will experience panoramic 360-degree aerial views of the 1,708-meter-wide sheet of falling water, the rising rainbows of the spray cloud, and the dramatic zigzagging basalt canyons downstream.',
      location: 'Victoria Falls Helipad / Zambezi River Airspace',
      duration: '12 Minutes (allow 1.5h total for transfers)',
      basePrice: '173.00',
      currency: 'USD',
      priceBasis: 'per_person',
      inclusions: ['12-minute helicopter flight with window views', 'Pre-flight safety briefing & pilot commentary', 'Hotel return transfers to/from helipad in Victoria Falls'],
      exclusions: ['Civil Aviation / Parks levy ($15/person payable at check-in)', 'In-flight commemorative video and photography'],
      suitability: ['All ages from 2 years up', 'Essential bucket-list experience', 'Keen aerial photographers'],
      isPublished: true,
      isFeatured: true,
      availabilityNote: 'Subject to partner confirmation & weather clearance',
      primaryMediaId: 'med_flight_angels_main',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_zambezi_extended_flight',
      operatorId: 'op_shearwater',
      name: 'Zambezi Gorge & Falls Extended Flight',
      slug: 'zambezi-gorge-and-falls-extended-flight',
      productType: 'activity',
      categorySlug: 'flight-air',
      shortDescription: 'Comprehensive 25-minute helicopter flight covering Victoria Falls, deep Batoka Gorge, and Zambezi National Park.',
      description: 'An expansive 25-minute aerial expedition that goes far beyond the Falls. After circling the cascades for sweeping photography from both sides, the pilot swoops low over the dramatic cliffs and raging rapids of Batoka Gorge, before flying upstream across the wilderness of Zambezi National Park to spot pods of hippos, elephants bathing, and buffalo herds from the air.',
      location: 'Victoria Falls Helipad, Batoka Gorge & Zambezi National Park',
      duration: '25 Minutes (allow 2h total for transfers)',
      basePrice: '328.00',
      currency: 'USD',
      priceBasis: 'per_person',
      inclusions: ['25-minute extended helicopter flight', 'Aerial wildlife spotting run over Zambezi National Park', 'Hotel return transfers in Victoria Falls'],
      exclusions: ['Civil Aviation / Parks levy ($15/person payable at check-in)', 'Souvenir digital flight media'],
      suitability: ['Wildlife lovers', 'Adventure seekers', 'Travelers wanting comprehensive aerial perspective'],
      isPublished: true,
      isFeatured: true,
      availabilityNote: 'Subject to partner confirmation & weather clearance',
      primaryMediaId: 'med_extended_flight_main',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_zambezi_explorer_cruise',
      operatorId: 'op_pure_africa',
      name: 'Zambezi Explorer Luxury Sunset Cruise',
      slug: 'zambezi-explorer-luxury-sunset-cruise',
      productType: 'activity',
      categorySlug: 'river-cruises',
      shortDescription: 'Signature eco-luxury catamaran cruise on the upper Zambezi with handcrafted canapés and premium drinks.',
      description: 'Glide along the tranquil waters of the upper Zambezi River aboard the pure solar-hybrid catamaran, Zambezi Explorer. Enjoy breathtaking views of elephants swimming between mid-river islands, hippos surfacing, and African fish eagles hunting, all framed by an unforgettable golden African sunset. Service includes freshly prepared hot and cold gourmet canapés and a curated open bar.',
      location: 'Pure Africa Waterfront Jetty, Upper Zambezi River',
      duration: '2.5 Hours',
      basePrice: '75.00',
      currency: 'USD',
      priceBasis: 'per_person',
      inclusions: ['2.5-hour sunset catamaran cruise', 'Full complimentary open bar (spirits, fine wines, beer, cocktails, soft drinks)', 'Chef-prepared hot & cold gourmet canapés', 'Hotel return transfers in Victoria Falls'],
      exclusions: ['Zambezi National Park river usage fee ($12/person)'],
      suitability: ['Couples', 'Families', 'Food & wine enthusiasts', 'Sunset lovers'],
      isPublished: true,
      isFeatured: true,
      availabilityNote: 'Departs daily at 16:00 (winter) / 16:30 (summer)',
      primaryMediaId: 'med_explorer_cruise_main',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_potjie_dining',
      operatorId: 'op_pure_africa',
      name: 'The Eatery Waterfront Potjie Dining',
      slug: 'the-eatery-waterfront-potjie-dining',
      productType: 'activity',
      categorySlug: 'dining-culinary',
      shortDescription: 'Authentic 3-course riverside dinner cooked slowly in traditional cast-iron potjies under African skies.',
      description: 'Set on the grass riverfront lawns of the Zambezi River with open fire braziers and lantern-lit tables, The Eatery presents an authentic southern African culinary tradition: the Potjiekos. Guests feast on slowly simmered game, beef, and vegetarian stews infused with wild herbs and red wine, accompanied by freshly baked potbrood, artisan salads, and delectable warm desserts.',
      location: 'Pure Africa Waterfront Jetty, Victoria Falls',
      duration: '2.5 Hours',
      basePrice: '45.00',
      currency: 'USD',
      priceBasis: 'per_person',
      inclusions: ['3-course traditional potjie dinner', 'Welcome cocktail on arrival', 'Campfire setting & live acoustic local entertainment', 'Return transfers from Victoria Falls hotels'],
      exclusions: ['Additional beverages from the cash/card bar', 'Gratuities'],
      suitability: ['Foodies', 'Romantic dining', 'Cultural explorers', 'Groups and families'],
      isPublished: true,
      isFeatured: false,
      availabilityNote: 'Evenings at 18:30 (reservation recommended)',
      primaryMediaId: 'med_potjie_main',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_lookout_cafe',
      operatorId: 'op_wildhorizons',
      name: 'The Lookout Café — Gorge Dining Experience',
      slug: 'lookout-cafe-gorge-dining',
      productType: 'activity',
      categorySlug: 'dining-culinary',
      shortDescription: 'Panoramic dining experience perched 120 meters above the turbulent waters of Batoka Gorge.',
      description: 'Perched dramatically on the precipice of the Batoka Gorge with uninhibited vistas of the historic Victoria Falls Bridge and the roaring Zambezi River below, The Lookout Café is one of southern Africa\'s most breathtaking dining locations. Enjoy contemporary pan-African fusion cuisine, artisanal burgers, crisp cocktails, and locally roasted coffees while watching gorge-swing jumpers dive into the canyon.',
      location: 'Batoka Gorge Cliff edge, Victoria Falls',
      duration: '2 Hours',
      basePrice: '55.00',
      currency: 'USD',
      priceBasis: 'per_person',
      inclusions: ['2-course à la carte dining experience voucher', 'Reserved cliffside table', 'Hotel return transfers in Victoria Falls'],
      exclusions: ['Specialty alcoholic spirits and cellar reserve wines', 'Adventure activities on site'],
      suitability: ['Panoramic scenic lovers', 'Couples', 'Casual diners', 'Spectators'],
      isPublished: true,
      isFeatured: true,
      availabilityNote: 'Open for lunch and dinner daily',
      primaryMediaId: 'med_lookout_main',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_white_water_rafting',
      operatorId: 'op_shearwater',
      name: 'Batoka Gorge White Water Rafting',
      slug: 'batoka-gorge-white-water-rafting',
      productType: 'activity',
      categorySlug: 'adventure-wildlife',
      shortDescription: 'World-renowned grade 5 white-water rafting through the roaring cataracts of the Zambezi.',
      description: 'Internationally recognized as one of the world\'s greatest one-day rafting adventures. Plunge through the legendary rapids of the Batoka Gorge — including "The Overland Truck-eater," "The Terminator," and "Oblivion." Led by internationally certified river guides with comprehensive safety kayak escorts, this is the ultimate adrenaline thrill on the planet.',
      location: 'Batoka Gorge (Rapid 1 to 19 or Rapid 11 to 24 depending on water season)',
      duration: 'Full Day (approx 7.5 hours)',
      basePrice: '140.00',
      currency: 'USD',
      priceBasis: 'per_person',
      inclusions: ['Full day grade 5 guided white water rafting', 'All commercial safety equipment (lifejacket, helmet, paddle)', 'Hearty cliff-top buffet lunch with cold beers and sodas', 'Return hotel transfers in Victoria Falls'],
      exclusions: ['National Parks river conservation levy ($10/person)', 'Photographer video/action shot package'],
      suitability: ['Adrenaline lovers', 'Good general fitness (requires hike out of 120m gorge)', 'Minimum age 15 years'],
      isPublished: true,
      isFeatured: true,
      availabilityNote: 'Low water season (Aug-Dec) / High water season (Jan-Jul, subject to river levels)',
      primaryMediaId: 'med_rafting_main',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_bridge_adventures',
      operatorId: 'op_shearwater',
      name: 'Victoria Falls Historic Bridge Adventures',
      slug: 'victoria-falls-historic-bridge-adventures',
      productType: 'activity',
      categorySlug: 'guided-tours',
      shortDescription: 'Historical walking tour and catwalk exploration of the iconic 1905 engineering marvel spanning the gorge.',
      description: 'Walk in the footsteps of Cecil John Rhodes\' vision to "bridge the Zambezi where the trains, as they pass, will catch the spray of the Falls." Put on a safety harness to walk beneath the bridge girders on the catwalk over the 111-meter gorge abyss, view historical photographs in the Visitor Center museum, and learn about the daring Victorian engineers who built it in England and assembled it here in 1905.',
      location: 'Victoria Falls Bridge (No-Man\'s-Land border zone)',
      duration: '1.5 Hours',
      basePrice: '40.00',
      currency: 'USD',
      priceBasis: 'per_person',
      inclusions: ['Guided historical tour by theatrical period guide', 'Catwalk girder exploration under the bridge with full safety harness', 'Access to Bridge Visitor Museum', 'Complimentary pass for border crossing'],
      exclusions: ['Bungee jumping, Bridge Swing, and Bridge Slide activities (bookable separately)', 'Personal drinks'],
      suitability: ['History and engineering buffs', 'Families', 'Curious travelers of all ages'],
      isPublished: true,
      isFeatured: false,
      availabilityNote: 'Tours depart every hour from 09:00 to 16:00',
      primaryMediaId: 'med_bridge_main',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_chobe_safari',
      operatorId: 'op_wildhorizons',
      name: 'Chobe National Park Day Safari',
      slug: 'chobe-national-park-day-safari',
      productType: 'activity',
      categorySlug: 'adventure-wildlife',
      shortDescription: 'Full-day safari expedition to Botswana’s world-famous elephant kingdom across the border.',
      description: 'Chobe National Park in neighboring Botswana boasts Africa\'s densest elephant population, with over 120,000 elephants. This seamless day trip includes hotel pickup in Victoria Falls, border assistance, a morning safari boat cruise on the Chobe River for up-close hippos and swimming elephants, a buffet lunch at Chobe Safari Lodge, and an afternoon 4x4 open safari vehicle game drive tracking lions, leopards, and giraffes.',
      location: 'Chobe National Park, Kasane, Botswana',
      duration: 'Full Day (07:30 to 18:00)',
      basePrice: '180.00',
      currency: 'USD',
      priceBasis: 'per_person',
      inclusions: ['Morning game viewing boat cruise on Chobe River', 'Afternoon 4x4 safari game drive in Chobe National Park', 'Buffet lunch at luxury river lodge', 'All cross-border transfers and border assistance from Victoria Falls'],
      exclusions: ['Botswana National Park fees ($15/person)', 'Visa fees for Botswana if applicable to traveler passport'],
      suitability: ['Big Five and wildlife safari lovers', 'Photographers', 'Families with children 6+'],
      isPublished: true,
      isFeatured: true,
      availabilityNote: 'Daily departures; passport required for cross-border transit',
      primaryMediaId: 'med_chobe_main',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_simunye_theatre',
      operatorId: 'op_rtg',
      name: 'Simunye — We Are One: Theatrical Experience',
      slug: 'simunye-theatrical-experience',
      productType: 'activity',
      categorySlug: 'dining-culinary',
      shortDescription: 'Mesmerizing evening musical production celebrating African folklore, acrobatics, and rhythm.',
      description: 'Simunye ("We Are One") is Victoria Falls\' premier theatrical evening show, hosted at the purpose-built auditorium at Victoria Falls Rainbow Hotel. Fusing traditional African storytelling, energetic contemporary choreography, soaring acrobatics, live drumming, and cutting-edge lighting, this internationally acclaimed production tells an inspiring tale of love, unity, and African heritage.',
      location: 'Simunye Theatre, Victoria Falls Rainbow Hotel',
      duration: '1.5 Hours',
      basePrice: '45.00',
      currency: 'USD',
      priceBasis: 'per_person',
      inclusions: ['Reserved tier theatre ticket for evening performance', 'Live musical, acrobatic & dramatic spectacle', 'Meet-and-greet photo opportunity with the cast after the show'],
      exclusions: ['Pre-show dinner and beverages', 'Transfers from outside Victoria Falls town'],
      suitability: ['All ages and families', 'Culture lovers', 'Ideal evening entertainment'],
      isPublished: true,
      isFeatured: false,
      availabilityNote: 'Show runs Tuesday through Sunday at 19:30',
      primaryMediaId: 'med_simunye_main',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_zambezi_game_drive',
      operatorId: 'op_wildhorizons',
      name: 'Zambezi National Park Safari Game Drive',
      slug: 'zambezi-national-park-safari-game-drive',
      productType: 'activity',
      categorySlug: 'adventure-wildlife',
      shortDescription: 'Open 4x4 guided wildlife safari tracking lions, elephants, leopards, and buffalo across pristine Zambezi wilderness.',
      description: 'Traverse the untamed wilderness of Zambezi National Park in a specialized open four-wheel-drive safari vehicle accompanied by a licensed professional guide. Track four of the Big Five along the banks of the Zambezi River and through mopane forests. Morning and afternoon safaris capture peak predator and game viewing hours.',
      location: 'Zambezi National Park Riverine & Chamabonda Sectors',
      duration: '3.5 Hours',
      basePrice: '70.00',
      currency: 'USD',
      priceBasis: 'per_person',
      inclusions: ['3.5-hour open 4x4 guided game drive', 'Professional armed naturalist guide', 'Mineral water, tea/coffee or sundowner drinks', 'Hotel return transfers in Victoria Falls'],
      exclusions: ['National Park conservation fee ($15/person)'],
      suitability: ['Wildlife lovers', 'Photographers', 'Families (children 4+)'],
      isPublished: true,
      isFeatured: true,
      availabilityNote: 'Morning (06:00) and Afternoon (15:00) departures daily',
      primaryMediaId: 'med_gamedrive_main',
      evidenceStatus: 'ESTABLISHED',
    },
    {
      id: 'prod_boma_dinner',
      operatorId: 'op_shearwater',
      name: 'The Boma — Dinner & Drum Show',
      slug: 'the-boma-dinner-and-drum-show',
      productType: 'activity',
      categorySlug: 'dining-culinary',
      shortDescription: 'Legendary celebration of Zimbabwean cuisine, cultural dance, face painting, and interactive djembe drumming.',
      description: 'The Boma – Place of Eating is a legendary cultural dining experience nestled in the Gusu forest. Guests are welcomed with traditional robes (chitenges), local beer sampling, and face painting, followed by an expansive 4-course feast including spit roasts, barbecue game meats, traditional potjies, and desserts. The evening culminates in an exhilarating interactive djembe drumming show where every guest is handed their own drum.',
      location: 'Victoria Falls Safari Concession',
      duration: '3 Hours',
      basePrice: '55.00',
      currency: 'USD',
      priceBasis: 'per_person',
      inclusions: ['Lavish 4-course buffet feast with game barbecues and traditional stews', 'Traditional face painting & welcoming chitenge robe', 'Interactive djembe drum session (each guest receives drum)', 'Live Shangaan dancers and acapella singers', 'Return hotel transfers in Victoria Falls'],
      exclusions: ['Alcoholic and specialty bar drinks', 'Gratuities'],
      suitability: ['All ages and families', 'Cultural explorers', 'Celebrations and groups'],
      isPublished: true,
      isFeatured: true,
      availabilityNote: 'Nightly at 19:00',
      primaryMediaId: 'med_boma_main',
      evidenceStatus: 'ESTABLISHED',
    }
  ];

  for (const p of prods) {
    if (tombstones.has(`products_${p.id}`)) continue;
    const existing = await db.select({ id: schema.products.id }).from(schema.products).where(eq(schema.products.id, p.id));
    if (existing.length > 0) {
      // Authoritative product already loaded from Firestore! NEVER OVERWRITE!
      continue;
    }
    // Only bootstrap if product does not exist in relational engine
    await db.insert(schema.products).values(p).onConflictDoNothing();
  }

  // 6. Rooms for Accommodation (depends on products)
  const roomList = [
    // A'Zambezi River Lodge
    {
      id: 'rm_azambezi_std',
      productId: 'prod_azambezi',
      propertyId: 'prop_azambezi',
      name: 'Standard Riverside Room',
      roomType: 'Standard',
      description: 'Comfortable air-conditioned room with king or twin beds, en-suite bathroom, and balcony overlooking lush indigenous gardens.',
      capacityAdults: 2,
      capacityChildren: 1,
      pricePerNight: '220.00',
      currency: 'USD',
      amenities: ['Air conditioning', 'Satellite TV', 'Tea & Coffee facilities', 'Private Balcony', 'Free Wi-Fi'],
      isAvailable: true,
    },
    {
      id: 'rm_azambezi_deluxe',
      productId: 'prod_azambezi',
      propertyId: 'prop_azambezi',
      name: 'River View Deluxe Room',
      roomType: 'Deluxe',
      description: 'Prime elevated positioning with direct sweeping views of the flowing Zambezi River, king bed, and private outdoor patio.',
      capacityAdults: 2,
      capacityChildren: 1,
      pricePerNight: '280.00',
      currency: 'USD',
      amenities: ['Direct Zambezi River view', 'Espresso machine', 'Mini bar fridge', 'Bathrobes & slippers', 'Balcony'],
      isAvailable: true,
    },
    {
      id: 'rm_azambezi_suite',
      productId: 'prod_azambezi',
      propertyId: 'prop_azambezi',
      name: 'Executive River Suite',
      roomType: 'Suite',
      description: 'Expansive luxury suite featuring an independent lounge salon, panoramic riverfront terrace, and soaking tub.',
      capacityAdults: 2,
      capacityChildren: 2,
      pricePerNight: '360.00',
      currency: 'USD',
      amenities: ['Separate living room', 'Panoramic river terrace', 'Deep soaking tub', 'VIP guest welcome', 'Complimentary minibar'],
      isAvailable: true,
    },

    // Victoria Falls Rainbow Hotel
    {
      id: 'rm_rainbow_std',
      productId: 'prod_rainbow',
      propertyId: 'prop_rainbow',
      name: 'Standard Twin / Double Room',
      roomType: 'Standard',
      description: 'Airy guestroom with private enclosed balcony, cooling tiled floors, air conditioning, and satellite television.',
      capacityAdults: 2,
      capacityChildren: 1,
      pricePerNight: '165.00',
      currency: 'USD',
      amenities: ['Air conditioning', 'En-suite shower/tub', 'Private balcony', 'Satellite TV', 'Safe'],
      isAvailable: true,
    },
    {
      id: 'rm_rainbow_deluxe',
      productId: 'prod_rainbow',
      propertyId: 'prop_rainbow',
      name: 'Deluxe Spray View Suite',
      roomType: 'Deluxe',
      description: 'Top-tier floor suite overlooking the gardens with direct views toward the rising spray plumes of Victoria Falls.',
      capacityAdults: 2,
      capacityChildren: 1,
      pricePerNight: '240.00',
      currency: 'USD',
      amenities: ['View of Falls spray plume', 'Lounge sitting area', 'Mini fridge', 'Bathrobes', 'Daily fruit basket'],
      isAvailable: true,
    },
    {
      id: 'rm_rainbow_family',
      productId: 'prod_rainbow',
      propertyId: 'prop_rainbow',
      name: 'Family Interconnecting Room',
      roomType: 'Family',
      description: 'Two interconnected bedrooms designed for traveling families or groups, sharing two private bathrooms.',
      capacityAdults: 2,
      capacityChildren: 3,
      pricePerNight: '290.00',
      currency: 'USD',
      amenities: ['Interconnecting bedrooms', '2 full en-suite bathrooms', '2 TVs', 'Generous wardrobe space'],
      isAvailable: true,
    },

    // Shearwater Explorers Village
    {
      id: 'rm_explorers_chalet',
      productId: 'prod_explorers',
      propertyId: 'prop_explorers',
      name: 'Standard Garden Chalet',
      roomType: 'Chalet',
      description: 'Private free-standing chalet surrounded by indigenous trees, walk-in shower, air conditioning, and personal patio.',
      capacityAdults: 2,
      capacityChildren: 0,
      pricePerNight: '110.00',
      currency: 'USD',
      amenities: ['Air conditioning', 'Walk-in rain shower', 'Private terrace', 'Room safe', 'Garden views'],
      isAvailable: true,
    },
    {
      id: 'rm_explorers_deluxe',
      productId: 'prod_explorers',
      propertyId: 'prop_explorers',
      name: 'Deluxe Village Suite',
      roomType: 'Deluxe',
      description: 'Spacious modern village room situated right alongside the main swimming pool with custom hardwood furnishings.',
      capacityAdults: 2,
      capacityChildren: 1,
      pricePerNight: '155.00',
      currency: 'USD',
      amenities: ['Poolside location', 'Lounge seating', 'Tea and coffee bar', 'High ceiling architecture'],
      isAvailable: true,
    },

    // Old Drift Lodge
    {
      id: 'rm_olddrift_tent',
      productId: 'prod_olddrift',
      propertyId: 'prop_olddrift',
      name: 'Luxury Tented Suite',
      roomType: 'Suite',
      description: 'Expansive riverfront canvas villa featuring private plunge pool, outdoor ball-and-claw Victorian bathtub, and king canopy bed.',
      capacityAdults: 2,
      capacityChildren: 0,
      pricePerNight: '680.00',
      currency: 'USD',
      amenities: ['Private plunge pool', 'Outdoor Victorian roll-top bath', 'Indoor & outdoor showers', 'Air conditioned bed canopy', 'Full minibar'],
      isAvailable: true,
    },
    {
      id: 'rm_olddrift_family',
      productId: 'prod_olddrift',
      propertyId: 'prop_olddrift',
      name: 'Family Tented Suite',
      roomType: 'Family',
      description: 'Two full en-suite tented bedrooms connected by an expansive private deck with central plunge pool overlooking the Zambezi.',
      capacityAdults: 2,
      capacityChildren: 2,
      pricePerNight: '980.00',
      currency: 'USD',
      amenities: ['Two en-suite bedrooms', 'Private central plunge pool', 'Panoramic river deck', 'Private family guide on request'],
      isAvailable: true,
    },

    // The Elephant Camp
    {
      id: 'rm_elephant_tent',
      productId: 'prod_elephantcamp',
      propertyId: 'prop_elephantcamp',
      name: 'Luxury Tented Suite',
      roomType: 'Suite',
      description: 'Breathtaking canvas retreat with private viewing deck over the Masuwe Gorge, private plunge pool, and indoor/outdoor showers.',
      capacityAdults: 2,
      capacityChildren: 1,
      pricePerNight: '750.00',
      currency: 'USD',
      amenities: ['Private infinity plunge pool', 'Gorge deck vistas', 'Freestanding oval bathtub', 'Fully stocked complimentary bar', 'Personal butler service'],
      isAvailable: true,
    }
  ];

  for (const r of roomList) {
    await db.insert(schema.rooms).values(r).onConflictDoNothing();
  }

  // 7. Packages
  const pkgList = [
    {
      id: 'pkg_essential_vf',
      name: 'Victoria Falls Essential Journey',
      slug: 'victoria-falls-essential-journey',
      tagline: 'The iconic 4-day introduction to Victoria Falls: rainforest, flight of angels & sunset cruise.',
      description: 'A seamlessly coordinated 4-day, 3-night holiday combining town accommodation at Shearwater Explorers Village with the three must-do experiences: a guided rainforest walking tour of the Falls, the world-famous 12-minute Flight of Angels helicopter flight, and a pure luxury sunset catamaran cruise on the Zambezi.',
      durationDays: 4,
      durationNights: 3,
      pricePerPerson: '680.00',
      currency: 'USD',
      highlights: [
        '3 nights at Shearwater Explorers Village with breakfast',
        '12-minute Flight of Angels scenic helicopter flight',
        'Zambezi Explorer luxury sunset cruise with canapés & open bar',
        'Victoria Falls Rainforest guided walking tour with poncho',
        'All airport and scheduled activity transfers included'
      ],
      inclusions: [
        '3 nights accommodation with daily breakfast',
        'All 3 signature activities as listed',
        'Return Victoria Falls International Airport transfers',
        'Dedicated Syntuc Explorer trip coordination'
      ],
      exclusions: ['Rainforest National Park entry fee ($50)', 'Helicopter aviation levy ($15)', 'River usage fee ($12)'],
      primaryImageUrl: 'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?auto=format&fit=crop&w=1200&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      isPublished: true,
    },
    {
      id: 'pkg_luxury_zambezi',
      name: 'Zambezi Luxury Safari & River Retreat',
      slug: 'zambezi-luxury-safari-retreat',
      tagline: 'All-inclusive 5-star riverfront canvas sanctuary, wildlife safaris & extended gorge helicopter flight.',
      description: 'Designed for the discerning traveler seeking complete wilderness immersion with unmatched luxury. Stay 3 nights at Old Drift Lodge in Zambezi National Park with private plunge pool, indulge in daily river boat safaris and game drives, fly on the 25-minute extended helicopter flight over Batoka Gorge, and dine suspended over the gorge at The Lookout Café.',
      durationDays: 4,
      durationNights: 3,
      pricePerPerson: '2450.00',
      currency: 'USD',
      highlights: [
        '3 nights all-inclusive luxury at Old Drift Lodge in Zambezi National Park',
        '25-minute Zambezi Gorge & Falls extended helicopter flight',
        'Private Zambezi Explorer sunset cruise with gourmet dinner',
        'The Lookout Café cliffside dining voucher',
        'Unlimited morning and evening wildlife game drives and river boat safaris'
      ],
      inclusions: [
        'All luxury accommodations, all meals and premium open bar',
        'All guided safari drives and river cruises inside Zambezi National Park',
        '25-minute extended helicopter tour',
        'Executive VIP airport transfers'
      ],
      exclusions: ['Park conservation fees ($15/day)', 'Helicopter park levy ($15)'],
      primaryImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
      isPublished: true,
    },
    {
      id: 'pkg_batoka_adventure',
      name: 'Batoka Adventure & Wilderness Duo',
      slug: 'batoka-adventure-and-wilderness-duo',
      tagline: 'High-adrenaline white-water rafting, Chobe Botswana safari, and panoramic hotel stay.',
      description: 'The definitive adventure package for active travelers. Base yourself for 2 nights at the Victoria Falls Rainbow Hotel overlooking the Falls spray. Conquer the world\'s greatest Grade 5 rapids on the Zambezi River with full-day rafting, and embark on a full-day cross-border safari to Botswana\'s Chobe National Park to witness hundreds of elephants along the Chobe River.',
      durationDays: 3,
      durationNights: 2,
      pricePerPerson: '590.00',
      currency: 'USD',
      highlights: [
        '2 nights at Victoria Falls Rainbow Hotel with breakfast',
        'Full-day Grade 5 Batoka Gorge White Water Rafting with gorge buffet lunch',
        'Full-day Chobe National Park Safari in Botswana (boat safari + 4x4 game drive + lodge buffet)',
        'Simunye African theatrical evening performance ticket'
      ],
      inclusions: [
        '2 nights accommodation with breakfast',
        'Full day white-water rafting with gear and guide',
        'Full day Chobe safari trip with border transfers and lunch',
        'Simunye theatre admission'
      ],
      exclusions: ['Parks river levy ($10)', 'Botswana park fee ($15)'],
      primaryImageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80',
      isPublished: true,
    },
    {
      id: 'pkg_sunset_gamedrive_combo',
      name: 'Sunset Cruise + Game Drive Package',
      slug: 'sunset-cruise-game-drive-package',
      tagline: 'Legacy combination package (Deactivated).',
      description: 'Historical packaged combination of Zambezi sunset cruise and Zambezi National Park safari drive. Deactivated in favor of standalone activities.',
      durationDays: 1,
      durationNights: 0,
      pricePerPerson: '180.00',
      currency: 'USD',
      highlights: ['Zambezi Sunset Cruise', 'National Park Safari Game Drive'],
      inclusions: ['Historical inclusion package'],
      exclusions: ['Parks fee'],
      primaryImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
      isPublished: false,
    }
  ];

  for (const pkg of pkgList) {
    if (tombstones.has(`packages_${pkg.id}`)) continue;
    const existingPkg = await db.select({ id: schema.packages.id }).from(schema.packages).where(eq(schema.packages.id, pkg.id));
    if (existingPkg.length > 0) continue;

    await db.insert(schema.packages).values(pkg).onConflictDoNothing();
    try {
      await persistPackageToFirestore(pkg as any);
    } catch (_) {}

    if (!tombstones.has(`products_${pkg.id}`)) {
      const existingProd = await db.select({ id: schema.products.id }).from(schema.products).where(eq(schema.products.id, pkg.id));
      if (existingProd.length === 0) {
        await db.insert(schema.products).values({
          id: pkg.id,
          operatorId: 'op_shearwater',
          name: pkg.name,
          slug: pkg.slug,
          productType: 'package',
          categorySlug: 'packages',
          shortDescription: pkg.tagline,
          description: pkg.description,
          location: 'Victoria Falls, Zimbabwe',
          duration: `${pkg.durationDays} Days / ${pkg.durationNights} Nights`,
          basePrice: pkg.pricePerPerson,
          currency: pkg.currency,
          priceBasis: 'per_person',
          inclusions: pkg.inclusions,
          exclusions: pkg.exclusions,
          suitability: ['Couples', 'Solo', 'Families'],
          isPublished: pkg.isPublished,
          isFeatured: true,
          availabilityNote: 'Confirmed with local partner operators',
          evidenceStatus: 'ESTABLISHED',
        }).onConflictDoNothing();
      }
    }
  }

}

/**
 * Seed fallback media assets for products that have ZERO media assets in database.
 * NEVER resurrects deleted assets (checks tombstones) and NEVER overwrites custom media.
 */
export async function seedFallbackMediaAssets(tombstones: Set<string> = new Set()) {
  const mediaList = [
    {
      id: 'med_azambezi_main',
      ownerType: 'product',
      ownerId: 'prod_azambezi',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: 'A\'Zambezi River Lodge riverfront lawn and private jetty on the Zambezi',
      altText: 'Riverfront view of A\'Zambezi River Lodge with lawns leading to Zambezi River',
      sourceName: 'Cresta Hotels Victoria Falls',
      verificationState: 'ESTABLISHED',
    },
    {
      id: 'med_rainbow_main',
      ownerType: 'product',
      ownerId: 'prod_rainbow',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: 'Victoria Falls Rainbow Hotel pool terrace with Moorish arches',
      altText: 'Swimming pool and sun terrace at Victoria Falls Rainbow Hotel',
      sourceName: 'Rainbow Tourism Group',
      verificationState: 'ESTABLISHED',
    },
    {
      id: 'med_explorers_main',
      ownerType: 'product',
      ownerId: 'prod_explorers',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: 'Shearwater Explorers Village garden pool and luxury chalets',
      altText: 'Tropical gardens and swimming pool at Shearwater Explorers Village',
      sourceName: 'Shearwater Victoria Falls',
      verificationState: 'ESTABLISHED',
    },
    {
      id: 'med_olddrift_main',
      ownerType: 'product',
      ownerId: 'prod_olddrift',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: 'Old Drift Lodge luxury tented deck overlooking the Zambezi River',
      altText: 'Canvas tented suite with timber deck right on the Zambezi River',
      sourceName: 'Machaba Safaris',
      verificationState: 'ESTABLISHED',
    },
    {
      id: 'med_elephantcamp_main',
      ownerType: 'product',
      ownerId: 'prod_elephantcamp',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1557053910-d9eadeed1c58?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1557053910-d9eadeed1c58?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: 'The Elephant Camp suite view overlooking the Masuwe gorge',
      altText: 'Luxury safari suite with plunge pool looking out over Victoria Falls reserve',
      sourceName: 'Wild Horizons',
      verificationState: 'ESTABLISHED',
    },
    {
      id: 'med_rainforest_main',
      ownerType: 'product',
      ownerId: 'prod_rainforest_walk',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: 'Victoria Falls rainforest viewpoint with rainbow over Main Falls',
      altText: 'Spectacular view of Victoria Falls from the lush rainforest walking trail',
      sourceName: 'Zimbabwe Parks & Wildlife',
      verificationState: 'ESTABLISHED',
    },
    {
      id: 'med_flight_angels_main',
      ownerType: 'product',
      ownerId: 'prod_flight_of_angels',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1508672019048-805b876b67e2?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1508672019048-805b876b67e2?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: '12-minute Flight of Angels scenic helicopter over Victoria Falls crest',
      altText: 'Helicopter flying directly over the Victoria Falls canyon with spray rainbows',
      sourceName: 'Shearwater Helicopters',
      verificationState: 'ESTABLISHED',
    },
    {
      id: 'med_extended_flight_main',
      ownerType: 'product',
      ownerId: 'prod_zambezi_extended_flight',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: '25-minute extended helicopter route over deep Batoka Gorge basalt zigzag',
      altText: 'Aerial view of the dramatic Batoka Gorge rapids and winding Zambezi canyon',
      sourceName: 'Shearwater Helicopters',
      verificationState: 'ESTABLISHED',
    },
    {
      id: 'med_explorer_cruise_main',
      ownerType: 'product',
      ownerId: 'prod_zambezi_explorer_cruise',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: 'Zambezi Explorer luxury catamaran cruising during African sunset',
      altText: 'Catamaran boat on the Zambezi River with golden sunset reflection',
      sourceName: 'Pure Africa',
      verificationState: 'ESTABLISHED',
    },
    {
      id: 'med_potjie_main',
      ownerType: 'product',
      ownerId: 'prod_potjie_dining',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: 'Traditional cast-iron potjiekos dining by the campfire at The Eatery',
      altText: 'Warm campfire dining under the stars on the Zambezi riverfront',
      sourceName: 'Pure Africa',
      verificationState: 'ESTABLISHED',
    },
    {
      id: 'med_lookout_main',
      ownerType: 'product',
      ownerId: 'prod_lookout_cafe',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: 'The Lookout Café dining deck perched over the Batoka Gorge',
      altText: 'Open restaurant deck overlooking the sheer cliffs of the Batoka Gorge',
      sourceName: 'Wild Horizons',
      verificationState: 'ESTABLISHED',
    },
    {
      id: 'med_rafting_main',
      ownerType: 'product',
      ownerId: 'prod_white_water_rafting',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1530866495561-507c9faab2ed?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1530866495561-507c9faab2ed?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: 'Adrenaline Grade 5 white-water rafting through the roaring Zambezi rapids',
      altText: 'Yellow raft battling massive white water waves in the Batoka Gorge',
      sourceName: 'Shearwater Adventures',
      verificationState: 'ESTABLISHED',
    },
    {
      id: 'med_bridge_main',
      ownerType: 'product',
      ownerId: 'prod_bridge_adventures',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: 'The historic 1905 Victoria Falls Bridge spanning the gorge',
      altText: 'Steel arch bridge crossing high above the Batoka Gorge with railway track',
      sourceName: 'Victoria Falls Bridge Company',
      verificationState: 'ESTABLISHED',
    },
    {
      id: 'med_chobe_main',
      ownerType: 'product',
      ownerId: 'prod_chobe_safari',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: 'Elephant herd drinking at Chobe River during afternoon boat safari',
      altText: 'Large herd of African elephants on the grassy banks of Chobe River',
      sourceName: 'Wild Horizons',
      verificationState: 'ESTABLISHED',
    },
    {
      id: 'med_simunye_main',
      ownerType: 'product',
      ownerId: 'prod_simunye_theatre',
      mediaType: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=1200&q=80',
      thumbnailUrl: 'https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      displayOrder: 1,
      caption: 'Simunye live theatrical performance celebrating African folklore',
      altText: 'Vibrant stage lighting and dancers performing at Simunye Victoria Falls theatre',
      sourceName: 'Simunye Theatre Victoria Falls',
      verificationState: 'ESTABLISHED',
    }
  ];

  for (const m of mediaList) {
    if (tombstones.has(`media_assets_${m.id}`)) {
      continue;
    }
    const existing = await db.select({ id: schema.mediaAssets.id }).from(schema.mediaAssets).where(eq(schema.mediaAssets.id, m.id));
    if (existing.length > 0) continue;

    // CRITICAL: If the product already has media in the database (custom coordinator uploads or hydrated assets),
    // NEVER resurrect or insert default generic Unsplash media!
    const ownerMedia = await db.select({ id: schema.mediaAssets.id }).from(schema.mediaAssets).where(eq(schema.mediaAssets.ownerId, m.ownerId));
    if (ownerMedia.length > 0) {
      continue;
    }

    await db.insert(schema.mediaAssets).values(m).onConflictDoNothing();
  }
}

/**
 * Backward compatibility wrapper
 */
export async function seedDatabase(tombstones: Set<string> = new Set()) {
  await seedMasterReferenceData();
  await seedBootstrapCatalog(tombstones);
  await seedFallbackMediaAssets(tombstones);
}
